on: [push]

jobs:
  uploadCoverageToCodecov:
    # 基本部分
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14.x"]
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install
        run: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

      - name: Quality check
        run: yarn qualityCheck

      # カスタム
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
